import 'dart:io';
import 'package:path/path.dart' as p;
import '../templates_embedded.dart';

enum StoreMode { gms, hms, rms, hybrid }

class AppCodeConfigurator {
  // New target directory: lib/generated/store_service
  final String _targetDir = 'lib/generated/store_service';
  final String _targetStoreService =
      'lib/generated/store_service/store_service.dart';
  final String _targetServicesDir = 'lib/generated/store_service/services';

  Future<void> apply(StoreMode mode) async {
    print(
      '🔧 Generating StoreService configuration for ${mode.name.toUpperCase()}...',
    );

    // Ensure target directories exist
    await Directory(_targetDir).create(recursive: true);
    await Directory(_targetServicesDir).create(recursive: true);

    // 1. Copy Service Templates (Firebase/HMS)
    if (mode == StoreMode.gms || mode == StoreMode.hybrid) {
      await _writeTemplate(
        firebaseServiceTemplate,
        '$_targetServicesDir/firebase_service.dart',
      );
    }

    if (mode == StoreMode.hms || mode == StoreMode.hybrid) {
      await _writeTemplate(
        hmsServiceTemplate,
        '$_targetServicesDir/hms_service.dart',
      );
    }

    if (mode == StoreMode.rms || mode == StoreMode.hybrid) {
      await _writeTemplate(
        rmsServiceTemplate,
        '$_targetServicesDir/rms_service.dart',
      );
    }

    // 2. Copy Interfaces
    await _writeTemplate(
      storeInterfacesTemplate,
      p.join(_targetDir, 'store_interfaces.dart'),
    );

    // 3. Generate StoreService
    String templateContent;
    switch (mode) {
      case StoreMode.gms:
        templateContent = storeServiceGmsTemplate;
        break;
      case StoreMode.hms:
        templateContent = storeServiceHmsTemplate;
        break;
      case StoreMode.rms:
        templateContent = storeServiceRmsTemplate;
        break;
      case StoreMode.hybrid:
        templateContent = storeServiceHybridTemplate;
        break;
    }

    await _writeTemplate(templateContent, _targetStoreService);
  }

  Future<void> _writeTemplate(String content, String targetPath) async {
    // Add Warning Header
    const header = '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// This code is generated by store_services_cli.
// Any changes to this file will be overwritten.

''';

    final targetFile = File(targetPath);
    await targetFile.create(recursive: true);
    await targetFile.writeAsString(header + content);
    print('  ✅ Generated $targetPath');
  }

  Future<void> remove() async {
    print('🧹 Cleaning generated store codes...');
    final dir = Directory(_targetDir);
    if (await dir.exists()) {
      await dir.delete(recursive: true);
      print('  ✅ Removed $_targetDir');
    }

    // Also try to clean old location just in case
    final oldFile = File('lib/store_service.dart');
    if (await oldFile.exists()) {
      await oldFile.delete();
      print('  ✅ Removed legacy lib/store_service.dart');
    }
    final oldDir = Directory('lib/services');
    if (await oldDir.exists()) {
      // Safety: Only delete known files?
      final f1 = File('lib/services/firebase_service.dart');
      if (await f1.exists()) await f1.delete();
      final f2 = File('lib/services/hms_service.dart');
      if (await f2.exists()) await f2.delete();

      // If empty, delete dir
      if (await oldDir.list().isEmpty) {
        await oldDir.delete();
        print('  ✅ Removed legacy lib/services directory');
      }
    }
  }
}
